// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXhH_lYKubONFv_Drb16meyYSs5tWbuqc',
    appId: '1:641969076786:web:6dfec2e7f02b2e4f379a2b',
    messagingSenderId: '641969076786',
    projectId: 'cultureconnect-gdsc',
    authDomain: 'cultureconnect-gdsc.firebaseapp.com',
    storageBucket: 'cultureconnect-gdsc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJnLNkx5xuxnB2k_vVDCUFISMG1__cb1Y',
    appId: '1:641969076786:android:1ed116980748095b379a2b',
    messagingSenderId: '641969076786',
    projectId: 'cultureconnect-gdsc',
    storageBucket: 'cultureconnect-gdsc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRkcMI541yGJQhR71uk3JN6brbJlvsXUA',
    appId: '1:641969076786:ios:69b9a06d18e1b78f379a2b',
    messagingSenderId: '641969076786',
    projectId: 'cultureconnect-gdsc',
    storageBucket: 'cultureconnect-gdsc.firebasestorage.app',
    iosBundleId: 'com.example.cultureconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRkcMI541yGJQhR71uk3JN6brbJlvsXUA',
    appId: '1:641969076786:ios:69b9a06d18e1b78f379a2b',
    messagingSenderId: '641969076786',
    projectId: 'cultureconnect-gdsc',
    storageBucket: 'cultureconnect-gdsc.firebasestorage.app',
    iosBundleId: 'com.example.cultureconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXhH_lYKubONFv_Drb16meyYSs5tWbuqc',
    appId: '1:641969076786:web:96ae0a2bd9269760379a2b',
    messagingSenderId: '641969076786',
    projectId: 'cultureconnect-gdsc',
    authDomain: 'cultureconnect-gdsc.firebaseapp.com',
    storageBucket: 'cultureconnect-gdsc.firebasestorage.app',
  );
}
